= Aufgabe 1
===================


Persona
|===
|Name |Hintergrund |Ziel

|Sam alnomiry
|Sam studiert als Austauschstudent Informatik an der HHU.
 Seine Sprachkenntnisse sind mittelmäßig. Er besucht die Veranstaltungen RDB
 und Rechnerarchitektur.
 Sam hat gar keine Programmierkenntnisse und kann mit dem PC auch nicht so besonders umgehen.
 Sam liest gerne Philosophie Bücher. Deswegen ist seine Abstraktionsfähigkeit besonders stark.
 Er ist mit den Plattformen der Uni unzufrieden, da er mit den vielen Plattformen überfordert ist und wünscht sich,
 dass das ganze irgendwann viel einfacher wird und mit Fremdsprachen unterstützt wird.
 Es gibt für jeweils seine Module unterschiedliche Bestehensgrenzen und er kann sie nicht alle merken.
|Sam möchte, dass das Abgabesystem nicht nur seine erreichten Punkte bei den Abgaben sieht, sondern auch, dass es einen
 Status gibt, wie seine Leistung mit einfachen Wörtern war, z.B, gut, ausreichend, nicht bestanden, etc.

|David Zimmermann
|David ist Organisator für die Veranstaltung Programmierung an der HHU.
 Er hat große Erfahrung in der Software Entwicklung und arbeitet in der Branche seit vielen Jahren.

 Er ist verheiratet und hat auch ein Kind. Durch die vielen Verantwortungen, die er trägt, leidet er immer unter
 Zeitmangel.

 David verteilt jede Woche die Abgaben der Studierende an den Korrekturen entsprechend ihrer Arbeitszeiten und ihrer
 Beschäftigungsarten. Diese Verteilung verlangt von ihm viel Zeit und Aufwand.

 David will an der Entwicklung des neuen Abgabesystems der HHU teilnehmen und das Projekt mit seiner Erfahrung
 unterstützen.
|David will, dass das Abgabesystem die Möglichkeit hat, die Abgaben der Studierenden automatisch an den KorrektorInnen
 entsprechend ihrer Beschäftigungsarten bzw. ihrer Arbeitszeiten verteilen kann, sodass er nur die Beschäftigungsarten
 der KorrektorInnen eingeben soll und durch eine einfache Berechnung werden die Abgaben fair verteilt.
|===

= Aufgabe 3
===================

.Name der Software
*********************************

HHU-Lern-manager ( HLM )

oder

Online-Studying-Manager ( OSM )

===================


= Aufgabe 4
===================


Teilsysteme
|===
|Name |Beschreibung
|Beschwerdesystem
|Das Beschwerdesystem gibt den Studierenden die Möglichkeit, sich über die verschiedenen Bestandteile der
 Lernveranstaltungen zu beschweren.
 Z. B., über Korrektur, Fehler in der Aufgaben, unklare Aufgabestellungen, Klausuren, etc.

 Dieses System soll dann automatisch die Beschwerden je nach Art der Beschwerde an dem zuständigen Personal
 ermitteln können, ohne dass der Student, sich darum kümmert, wer für welchen Teil der Veranstaltung verantwortlich ist
 und an welche E-Mail-Adresse die Beschwerde geschickt werden soll.

 Der Student/in sucht sich die Art der Beschwerden aus und gemäß dieser Wahl wird dann die Beschwerde
 an der richtigen Person vermittelt.

 Die Studierende sollen auch den Status ihrer Beschwerden verfolgen können,
 z.B., in Bearbeitung, genehmigt, abgelehnt, siehe Antwort, etc.

 Die Verantwortlichen können dann auf die Beschwerden antworten.

 Der ganze Prozess muss zeitlich dokumentiert werden.

|Column 1, row 2
|Column 2, row 2
|===
