= Aufgabe 1
===================


Persona
|===
|Name |Hintergrund |Ziel

|Sam alnomiry
|Sam studiert als Austauschstudent Informatik an der HHU. Seine Sprachkenntnisse sind mittelmäßig.
 Er besucht die Veranschtaltungen RDB und Rechnerarchitektur.
 Sam hat gar keine Programmierkenntnisse und kann mit dem PC auch nicht so besonders umgehen.

 Sam liest gerne philosophie Bücher. Deswegen ist seine abstraktionsfähigkeit besonders stark.

 Er ist mit den Plattformen der Uni unzufrieden, da er mit den vielen platformen überfordert ist und wünscht sich, dass
 das ganze irgenwann viel einfacher wird und mit Fremdsprachen unterstützt wird.

 Es gibt für jeweils seine Modulle unterschiedliche Bestehensgrenzen und er kann sie nicht alle merken.

|Sam möchte, dass das Abgabesystem nicht nur seine erreichten Punkte bei den Abgaben sieht, sondern auch dass es einen
 Stutus gibt, wie seine Leistung mit einfachen wörtern war, z.B, gut, ausreichend, nicht bestanden, etc.

|David Zimmermann
|David ist Organisator für die Veranstaltung Programmierung an dr HHU.
 Er hat große Erfahrung in der Software Entwicklung und arbeitet in der Branche seit vielen Jahren.

 Er ist vereihatet und hat auch ein Kind. Durch die vielen Verantwochtungen, die er trägt, leidet er immer unter
 Zeilmangel.

 David verteilt jede Woche die Abgaben der Studierende an den Korrekturen entsprechend ihrer Arbeitzeiten und ihrer
 Beschäftigungsart. Diese Verteilung verlangt von ihm viel Zeit und Aufwand.

 David will an der Entwicklung des neuen Abgabesystem der HHU teilnehmen und das Projekt mit seiner Erfahrung
 unterstützen.
|David will, dass das Abgabesystem die Möglichkeit hat, die Abgaben der Studierenden automatisch an den Korrekturen
entsprechend ihrer Beschäftigungsart bzw. ihrer Arbeitszeiten verteilen kann, sodass er nur die Beschäftigungsart der
Korrekturen eingeben soll und durch eine einfache Berechnung werden die Abgaben fair verteilt.

|===
